Fixed local vagrant

diff --git a/playbooks/templates/php/php5-fpm.init b/playbooks/templates/php/php5-fpm.init
--- a/playbooks/templates/php/php5-fpm.init
+++ b/playbooks/templates/php/php5-fpm.init
@@ -13,140 +13,146 @@
 prefix=
 exec_prefix=
 
-php_fpm_BIN=/usr/local/sbin/php-fpm
-php_fpm_CONF=/etc/php-{{ php_version }}/fpm/php-fpm.conf
-php_fpm_PID=/var/run/php5-fpm.pid
+php_fpm_BIN=/usr/local/php-{{ php_version }}/sbin/php-fpm
+php_fpm_CONF=/etc/php-{{ php_version }}/php-fpm.conf
+php_fpm_PID=/var/run/php-{{ php_version }}-fpm.pid
 
 
 php_opts="--fpm-config $php_fpm_CONF --pid $php_fpm_PID"
 
 
 wait_for_pid () {
-	try=0
+    try=0
 
-	while test $try -lt 35 ; do
+    while test $try -lt 35 ; do
 
-		case "$1" in
-			'created')
-			if [ -f "$2" ] ; then
-				try=''
-				break
-			fi
-			;;
+        case "$1" in
+            'created')
+            if [ -f "$2" ] ; then
+                try=''
+                break
+            fi
+            ;;
 
-			'removed')
-			if [ ! -f "$2" ] ; then
-				try=''
-				break
-			fi
-			;;
-		esac
+            'removed')
+            if [ ! -f "$2" ] ; then
+                try=''
+                break
+            fi
+            ;;
+        esac
 
-		echo -n .
-		try=`expr $try + 1`
-		sleep 1
+        echo -n .
+        try=`expr $try + 1`
+        sleep 1
 
-	done
+    done
 
 }
 
 case "$1" in
-	start)
-		echo -n "Starting php-fpm "
+    start)
+        echo -n "Starting php-fpm "
 
-		$php_fpm_BIN --daemonize $php_opts
+        $php_fpm_BIN $php_opts
 
-		if [ "$?" != 0 ] ; then
-			echo " failed"
-			exit 1
-		fi
+        if [ "$?" != 0 ] ; then
+            echo " failed"
+            exit 1
+        fi
 
-		wait_for_pid created $php_fpm_PID
+        wait_for_pid created $php_fpm_PID
 
-		if [ -n "$try" ] ; then
-			echo " failed"
-			exit 1
-		else
-			echo " done"
-		fi
-	;;
+        if [ -n "$try" ] ; then
+            echo " failed"
+            exit 1
+        else
+            echo " done"
+        fi
+    ;;
 
-	stop)
-		echo -n "Gracefully shutting down php-fpm "
+    stop)
+        echo -n "Gracefully shutting down php-fpm "
 
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
+        if [ ! -r $php_fpm_PID ] ; then
+            echo "warning, no pid file found - php-fpm is not running ?"
+            exit 1
+        fi
 
-		kill -QUIT `cat $php_fpm_PID`
+        kill -QUIT `cat $php_fpm_PID`
 
-		wait_for_pid removed $php_fpm_PID
+        wait_for_pid removed $php_fpm_PID
 
-		if [ -n "$try" ] ; then
-			echo " failed. Use force-quit"
-			exit 1
-		else
-			echo " done"
-		fi
-	;;
+        if [ -n "$try" ] ; then
+            echo " failed. Use force-quit"
+            exit 1
+        else
+            echo " done"
+        fi
+    ;;
 
-	status)
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "php-fpm is stopped"
-			exit 0
-		fi
+    status)
+        if [ ! -r $php_fpm_PID ] ; then
+            echo "php-fpm is stopped"
+            exit 1
+        fi
 
-		PID=`cat $php_fpm_PID`
-		if ps -p $PID | grep -q $PID; then
-			echo "php-fpm (pid $PID) is running..."
-		else
-			echo "php-fpm dead but pid file exists"
-		fi
-	;;
+        PID=`cat $php_fpm_PID`
+        if ps -p $PID | grep -q $PID; then
+            echo "php-fpm (pid $PID) is running..."
+            exit 0
+        else
+            echo "php-fpm dead but pid file exists"
+            exit 1
+        fi
+    ;;
 
-	force-quit)
-		echo -n "Terminating php-fpm "
+    try-restart)
+        $0 status && $0 restart
+    ;;
 
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
+    force-quit)
+        echo -n "Terminating php-fpm "
 
-		kill -TERM `cat $php_fpm_PID`
+        if [ ! -r $php_fpm_PID ] ; then
+            echo "warning, no pid file found - php-fpm is not running ?"
+            exit 1
+        fi
 
-		wait_for_pid removed $php_fpm_PID
+        kill -TERM `cat $php_fpm_PID`
 
-		if [ -n "$try" ] ; then
-			echo " failed"
-			exit 1
-		else
-			echo " done"
-		fi
-	;;
+        wait_for_pid removed $php_fpm_PID
 
-	restart)
-		$0 stop
-		$0 start
-	;;
+        if [ -n "$try" ] ; then
+            echo " failed"
+            exit 1
+        else
+            echo " done"
+        fi
+    ;;
 
-	reload)
+    restart)
+        $0 stop
+        $0 start
+    ;;
 
-		echo -n "Reload service php-fpm "
+    reload)
 
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
+        echo -n "Reload service php-fpm "
 
-		kill -USR2 `cat $php_fpm_PID`
+        if [ ! -r $php_fpm_PID ] ; then
+            echo "warning, no pid file found - php-fpm is not running ?"
+            exit 1
+        fi
 
-		echo " done"
-	;;
+        kill -USR2 `cat $php_fpm_PID`
 
-	*)
-		echo "Usage: $0 {start|stop|force-quit|restart|reload|status}"
-		exit 1
-	;;
+        echo " done"
+    ;;
+
+    *)
+        echo "Usage: $0 {start|stop|force-quit|restart|try-restart|reload|status}"
+        exit 1
+    ;;
 
 esac
